name: Teleportation
version: '1.0.2'
main: com.github.rokkuu.Teleportation.Teleportation
api-version: 1.18
authors: [ rokkuu ]
website: github.com/rokkuu
commands:
  tpr:
    description: Allows teleportation to players
    usage: /<command>
    aliases:
      - tpa
      - teleportTo
  tpac:
    description: Accept teleportation from a player
    usage: /<command>
    aliases:
      - /tpaccept


